/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    Organisation,
    OrganisationFromJSON,
    OrganisationToJSON,
    UpdateOrganisationDto,
    UpdateOrganisationDtoFromJSON,
    UpdateOrganisationDtoToJSON,
} from '../models';

export interface OrganisationControllerFindOneRequest {
    uuid: string;
}

export interface OrganisationControllerRemoveRequest {
    uuid: string;
}

export interface OrganisationControllerUpdateRequest {
    uuid: string;
    updateOrganisationDto: UpdateOrganisationDto;
}

/**
 * OrganisationsApi - interface
 * 
 * @export
 * @interface OrganisationsApiInterface
 */
export interface OrganisationsApiInterface {
    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerFindAllForUserRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Organisation>>>;

    /**
     */
    organisationControllerFindAllForUser(initOverrides?: RequestInit): Promise<Array<Organisation>>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerFindOneRaw(requestParameters: OrganisationControllerFindOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerFindOne(requestParameters: OrganisationControllerFindOneRequest, initOverrides?: RequestInit): Promise<Organisation>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerRemoveRaw(requestParameters: OrganisationControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerRemove(requestParameters: OrganisationControllerRemoveRequest, initOverrides?: RequestInit): Promise<Organisation>;

    /**
     * 
     * @param {string} uuid 
     * @param {UpdateOrganisationDto} updateOrganisationDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof OrganisationsApiInterface
     */
    organisationControllerUpdateRaw(requestParameters: OrganisationControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>>;

    /**
     */
    organisationControllerUpdate(requestParameters: OrganisationControllerUpdateRequest, initOverrides?: RequestInit): Promise<Organisation>;

}

/**
 * 
 */
export class OrganisationsApi extends runtime.BaseAPI implements OrganisationsApiInterface {

    /**
     */
    async organisationControllerFindAllForUserRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<Organisation>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(OrganisationFromJSON));
    }

    /**
     */
    async organisationControllerFindAllForUser(initOverrides?: RequestInit): Promise<Array<Organisation>> {
        const response = await this.organisationControllerFindAllForUserRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async organisationControllerFindOneRaw(requestParameters: OrganisationControllerFindOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerFindOne(requestParameters: OrganisationControllerFindOneRequest, initOverrides?: RequestInit): Promise<Organisation> {
        const response = await this.organisationControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async organisationControllerRemoveRaw(requestParameters: OrganisationControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerRemove(requestParameters: OrganisationControllerRemoveRequest, initOverrides?: RequestInit): Promise<Organisation> {
        const response = await this.organisationControllerRemoveRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async organisationControllerUpdateRaw(requestParameters: OrganisationControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Organisation>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling organisationControllerUpdate.');
        }

        if (requestParameters.updateOrganisationDto === null || requestParameters.updateOrganisationDto === undefined) {
            throw new runtime.RequiredError('updateOrganisationDto','Required parameter requestParameters.updateOrganisationDto was null or undefined when calling organisationControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/organisation/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateOrganisationDtoToJSON(requestParameters.updateOrganisationDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => OrganisationFromJSON(jsonValue));
    }

    /**
     */
    async organisationControllerUpdate(requestParameters: OrganisationControllerUpdateRequest, initOverrides?: RequestInit): Promise<Organisation> {
        const response = await this.organisationControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
