/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    NoActionTestMeta,
    NoActionTestMetaFromJSON,
    NoActionTestMetaFromJSONTyped,
    NoActionTestMetaToJSON,
    TwitterUserMentionMeta,
    TwitterUserMentionMetaFromJSON,
    TwitterUserMentionMetaFromJSONTyped,
    TwitterUserMentionMetaToJSON,
} from './';

/**
 * 
 * @export
 * @interface AllMetaTypes
 */
export interface AllMetaTypes {
    /**
     * 
     * @type {TwitterUserMentionMeta}
     * @memberof AllMetaTypes
     */
    twitterUserMentionMeta?: TwitterUserMentionMeta;
    /**
     * 
     * @type {NoActionTestMeta}
     * @memberof AllMetaTypes
     */
    noActionTestMeta?: NoActionTestMeta;
}

export function AllMetaTypesFromJSON(json: any): AllMetaTypes {
    return AllMetaTypesFromJSONTyped(json, false);
}

export function AllMetaTypesFromJSONTyped(json: any, ignoreDiscriminator: boolean): AllMetaTypes {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'twitterUserMentionMeta': !exists(json, 'twitterUserMentionMeta') ? undefined : TwitterUserMentionMetaFromJSON(json['twitterUserMentionMeta']),
        'noActionTestMeta': !exists(json, 'noActionTestMeta') ? undefined : NoActionTestMetaFromJSON(json['noActionTestMeta']),
    };
}

export function AllMetaTypesToJSON(value?: AllMetaTypes | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'twitterUserMentionMeta': TwitterUserMentionMetaToJSON(value.twitterUserMentionMeta),
        'noActionTestMeta': NoActionTestMetaToJSON(value.noActionTestMeta),
    };
}


