/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface BinanceAverageAboveMeta
 */
export interface BinanceAverageAboveMeta {
    /**
     * 
     * @type {string}
     * @memberof BinanceAverageAboveMeta
     */
    binanceSymbol: string;
    /**
     * 
     * @type {number}
     * @memberof BinanceAverageAboveMeta
     */
    aboveLimit: number;
}

export function BinanceAverageAboveMetaFromJSON(json: any): BinanceAverageAboveMeta {
    return BinanceAverageAboveMetaFromJSONTyped(json, false);
}

export function BinanceAverageAboveMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): BinanceAverageAboveMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'binanceSymbol': json['binanceSymbol'],
        'aboveLimit': json['aboveLimit'],
    };
}

export function BinanceAverageAboveMetaToJSON(value?: BinanceAverageAboveMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'binanceSymbol': value.binanceSymbol,
        'aboveLimit': value.aboveLimit,
    };
}

