/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AllMetaTypes,
    AllMetaTypesFromJSON,
    AllMetaTypesFromJSONTyped,
    AllMetaTypesToJSON,
    TriggerTypeEnum,
    TriggerTypeEnumFromJSON,
    TriggerTypeEnumFromJSONTyped,
    TriggerTypeEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateTriggerDto
 */
export interface CreateTriggerDto {
    /**
     * 
     * @type {TriggerTypeEnum}
     * @memberof CreateTriggerDto
     */
    triggerType: TriggerTypeEnum;
    /**
     * 
     * @type {AllMetaTypes}
     * @memberof CreateTriggerDto
     */
    allMeta: AllMetaTypes;
}

export function CreateTriggerDtoFromJSON(json: any): CreateTriggerDto {
    return CreateTriggerDtoFromJSONTyped(json, false);
}

export function CreateTriggerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateTriggerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'triggerType': TriggerTypeEnumFromJSON(json['triggerType']),
        'allMeta': AllMetaTypesFromJSON(json['allMeta']),
    };
}

export function CreateTriggerDtoToJSON(value?: CreateTriggerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'triggerType': TriggerTypeEnumToJSON(value.triggerType),
        'allMeta': AllMetaTypesToJSON(value.allMeta),
    };
}


