/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    Person,
    PersonFromJSON,
    PersonFromJSONTyped,
    PersonToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateOrganisationDto
 */
export interface CreateOrganisationDto {
    /**
     * 
     * @type {Array<Person>}
     * @memberof CreateOrganisationDto
     */
    members: Array<Person>;
    /**
     * 
     * @type {Person}
     * @memberof CreateOrganisationDto
     */
    owner: Person;
    /**
     * 
     * @type {string}
     * @memberof CreateOrganisationDto
     */
    name: string;
}

export function CreateOrganisationDtoFromJSON(json: any): CreateOrganisationDto {
    return CreateOrganisationDtoFromJSONTyped(json, false);
}

export function CreateOrganisationDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateOrganisationDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'members': ((json['members'] as Array<any>).map(PersonFromJSON)),
        'owner': PersonFromJSON(json['owner']),
        'name': json['name'],
    };
}

export function CreateOrganisationDtoToJSON(value?: CreateOrganisationDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'members': ((value.members as Array<any>).map(PersonToJSON)),
        'owner': PersonToJSON(value.owner),
        'name': value.name,
    };
}


