/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    RunningStateEnum,
    RunningStateEnumFromJSON,
    RunningStateEnumFromJSONTyped,
    RunningStateEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface CreateCustomBotDto
 */
export interface CreateCustomBotDto {
    /**
     * 
     * @type {string}
     * @memberof CreateCustomBotDto
     */
    name: string;
    /**
     * 
     * @type {number}
     * @memberof CreateCustomBotDto
     */
    runEveryInSeconds: number;
    /**
     * 
     * @type {RunningStateEnum}
     * @memberof CreateCustomBotDto
     */
    runningState: RunningStateEnum;
}

export function CreateCustomBotDtoFromJSON(json: any): CreateCustomBotDto {
    return CreateCustomBotDtoFromJSONTyped(json, false);
}

export function CreateCustomBotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateCustomBotDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'name': json['name'],
        'runEveryInSeconds': json['runEveryInSeconds'],
        'runningState': RunningStateEnumFromJSON(json['runningState']),
    };
}

export function CreateCustomBotDtoToJSON(value?: CreateCustomBotDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'name': value.name,
        'runEveryInSeconds': value.runEveryInSeconds,
        'runningState': RunningStateEnumToJSON(value.runningState),
    };
}


