/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface NoActionTestMeta
 */
export interface NoActionTestMeta {
    /**
     * 
     * @type {string}
     * @memberof NoActionTestMeta
     */
    testString: string;
}

export function NoActionTestMetaFromJSON(json: any): NoActionTestMeta {
    return NoActionTestMetaFromJSONTyped(json, false);
}

export function NoActionTestMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): NoActionTestMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'testString': json['testString'],
    };
}

export function NoActionTestMetaToJSON(value?: NoActionTestMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'testString': value.testString,
    };
}


