/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum TriggerTypeEnum {
    TWITTER_USER_MENTION = 'TWITTER_USER_MENTION',
    NO_ACTION_DEFAULT = 'NO_ACTION_DEFAULT'
}

export function TriggerTypeEnumFromJSON(json: any): TriggerTypeEnum {
    return TriggerTypeEnumFromJSONTyped(json, false);
}

export function TriggerTypeEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): TriggerTypeEnum {
    return json as TriggerTypeEnum;
}

export function TriggerTypeEnumToJSON(value?: TriggerTypeEnum | null): any {
    return value as any;
}

