/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface TwitterUserMentionMeta
 */
export interface TwitterUserMentionMeta {
    /**
     * 
     * @type {string}
     * @memberof TwitterUserMentionMeta
     */
    twitterUserName: string;
    /**
     * 
     * @type {string}
     * @memberof TwitterUserMentionMeta
     */
    mentionText: string;
}

export function TwitterUserMentionMetaFromJSON(json: any): TwitterUserMentionMeta {
    return TwitterUserMentionMetaFromJSONTyped(json, false);
}

export function TwitterUserMentionMetaFromJSONTyped(json: any, ignoreDiscriminator: boolean): TwitterUserMentionMeta {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'twitterUserName': json['twitterUserName'],
        'mentionText': json['mentionText'],
    };
}

export function TwitterUserMentionMetaToJSON(value?: TwitterUserMentionMeta | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'twitterUserName': value.twitterUserName,
        'mentionText': value.mentionText,
    };
}


