/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    TriggerTypeEnum,
    TriggerTypeEnumFromJSON,
    TriggerTypeEnumFromJSONTyped,
    TriggerTypeEnumToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateTriggerDto
 */
export interface UpdateTriggerDto {
    /**
     * 
     * @type {string}
     * @memberof UpdateTriggerDto
     */
    updateSchedule: string;
    /**
     * 
     * @type {TriggerTypeEnum}
     * @memberof UpdateTriggerDto
     */
    triggerType: TriggerTypeEnum;
    /**
     * 
     * @type {object}
     * @memberof UpdateTriggerDto
     */
    meta: object;
    /**
     * 
     * @type {number}
     * @memberof UpdateTriggerDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTriggerDto
     */
    uuid: string;
}

export function UpdateTriggerDtoFromJSON(json: any): UpdateTriggerDto {
    return UpdateTriggerDtoFromJSONTyped(json, false);
}

export function UpdateTriggerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTriggerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'updateSchedule': json['updateSchedule'],
        'triggerType': TriggerTypeEnumFromJSON(json['triggerType']),
        'meta': json['meta'],
        'id': json['id'],
        'uuid': json['uuid'],
    };
}

export function UpdateTriggerDtoToJSON(value?: UpdateTriggerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'updateSchedule': value.updateSchedule,
        'triggerType': TriggerTypeEnumToJSON(value.triggerType),
        'meta': value.meta,
        'id': value.id,
        'uuid': value.uuid,
    };
}


