/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    UpdateTriggerDto,
    UpdateTriggerDtoFromJSON,
    UpdateTriggerDtoFromJSONTyped,
    UpdateTriggerDtoToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateCustomBotDto
 */
export interface UpdateCustomBotDto {
    /**
     * 
     * @type {Array<UpdateTriggerDto>}
     * @memberof UpdateCustomBotDto
     */
    triggers: Array<UpdateTriggerDto>;
    /**
     * 
     * @type {string}
     * @memberof UpdateCustomBotDto
     */
    checkSchedule: string;
}

export function UpdateCustomBotDtoFromJSON(json: any): UpdateCustomBotDto {
    return UpdateCustomBotDtoFromJSONTyped(json, false);
}

export function UpdateCustomBotDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateCustomBotDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'triggers': ((json['triggers'] as Array<any>).map(UpdateTriggerDtoFromJSON)),
        'checkSchedule': json['checkSchedule'],
    };
}

export function UpdateCustomBotDtoToJSON(value?: UpdateCustomBotDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'triggers': ((value.triggers as Array<any>).map(UpdateTriggerDtoToJSON)),
        'checkSchedule': value.checkSchedule,
    };
}


