/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateCustomBotDto,
    CreateCustomBotDtoFromJSON,
    CreateCustomBotDtoToJSON,
    CustomBot,
    CustomBotFromJSON,
    CustomBotToJSON,
    UpdateCustomBotDto,
    UpdateCustomBotDtoFromJSON,
    UpdateCustomBotDtoToJSON,
} from '../models';

export interface CustomBotControllerCreateRequest {
    createCustomBotDto: CreateCustomBotDto;
}

export interface CustomBotControllerFindOneRequest {
    uuid: string;
}

export interface CustomBotControllerRemoveRequest {
    uuid: string;
}

export interface CustomBotControllerUpdateRequest {
    uuid: string;
    updateCustomBotDto: UpdateCustomBotDto;
}

export interface TwitterClientControllerFindAllRequest {
    twitterName: string;
    query: string;
    since: Date;
}

/**
 * CustomBotApi - interface
 * 
 * @export
 * @interface CustomBotApiInterface
 */
export interface CustomBotApiInterface {
    /**
     * 
     * @param {CreateCustomBotDto} createCustomBotDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    customBotControllerCreateRaw(requestParameters: CustomBotControllerCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>>;

    /**
     */
    customBotControllerCreate(requestParameters: CustomBotControllerCreateRequest, initOverrides?: RequestInit): Promise<CustomBot>;

    /**
     * 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    customBotControllerFindAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<CustomBot>>>;

    /**
     */
    customBotControllerFindAll(initOverrides?: RequestInit): Promise<Array<CustomBot>>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    customBotControllerFindOneRaw(requestParameters: CustomBotControllerFindOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>>;

    /**
     */
    customBotControllerFindOne(requestParameters: CustomBotControllerFindOneRequest, initOverrides?: RequestInit): Promise<CustomBot>;

    /**
     * 
     * @param {string} uuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    customBotControllerRemoveRaw(requestParameters: CustomBotControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    customBotControllerRemove(requestParameters: CustomBotControllerRemoveRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {string} uuid 
     * @param {UpdateCustomBotDto} updateCustomBotDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    customBotControllerUpdateRaw(requestParameters: CustomBotControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>>;

    /**
     */
    customBotControllerUpdate(requestParameters: CustomBotControllerUpdateRequest, initOverrides?: RequestInit): Promise<CustomBot>;

    /**
     * 
     * @param {string} twitterName 
     * @param {string} query 
     * @param {Date} since 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof CustomBotApiInterface
     */
    twitterClientControllerFindAllRaw(requestParameters: TwitterClientControllerFindAllRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<object>>>;

    /**
     */
    twitterClientControllerFindAll(requestParameters: TwitterClientControllerFindAllRequest, initOverrides?: RequestInit): Promise<Array<object>>;

}

/**
 * 
 */
export class CustomBotApi extends runtime.BaseAPI implements CustomBotApiInterface {

    /**
     */
    async customBotControllerCreateRaw(requestParameters: CustomBotControllerCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>> {
        if (requestParameters.createCustomBotDto === null || requestParameters.createCustomBotDto === undefined) {
            throw new runtime.RequiredError('createCustomBotDto','Required parameter requestParameters.createCustomBotDto was null or undefined when calling customBotControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot`,
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateCustomBotDtoToJSON(requestParameters.createCustomBotDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomBotFromJSON(jsonValue));
    }

    /**
     */
    async customBotControllerCreate(requestParameters: CustomBotControllerCreateRequest, initOverrides?: RequestInit): Promise<CustomBot> {
        const response = await this.customBotControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customBotControllerFindAllRaw(initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<CustomBot>>> {
        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => jsonValue.map(CustomBotFromJSON));
    }

    /**
     */
    async customBotControllerFindAll(initOverrides?: RequestInit): Promise<Array<CustomBot>> {
        const response = await this.customBotControllerFindAllRaw(initOverrides);
        return await response.value();
    }

    /**
     */
    async customBotControllerFindOneRaw(requestParameters: CustomBotControllerFindOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling customBotControllerFindOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomBotFromJSON(jsonValue));
    }

    /**
     */
    async customBotControllerFindOne(requestParameters: CustomBotControllerFindOneRequest, initOverrides?: RequestInit): Promise<CustomBot> {
        const response = await this.customBotControllerFindOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async customBotControllerRemoveRaw(requestParameters: CustomBotControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling customBotControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async customBotControllerRemove(requestParameters: CustomBotControllerRemoveRequest, initOverrides?: RequestInit): Promise<void> {
        await this.customBotControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     */
    async customBotControllerUpdateRaw(requestParameters: CustomBotControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<CustomBot>> {
        if (requestParameters.uuid === null || requestParameters.uuid === undefined) {
            throw new runtime.RequiredError('uuid','Required parameter requestParameters.uuid was null or undefined when calling customBotControllerUpdate.');
        }

        if (requestParameters.updateCustomBotDto === null || requestParameters.updateCustomBotDto === undefined) {
            throw new runtime.RequiredError('updateCustomBotDto','Required parameter requestParameters.updateCustomBotDto was null or undefined when calling customBotControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{uuid}`.replace(`{${"uuid"}}`, encodeURIComponent(String(requestParameters.uuid))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateCustomBotDtoToJSON(requestParameters.updateCustomBotDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => CustomBotFromJSON(jsonValue));
    }

    /**
     */
    async customBotControllerUpdate(requestParameters: CustomBotControllerUpdateRequest, initOverrides?: RequestInit): Promise<CustomBot> {
        const response = await this.customBotControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async twitterClientControllerFindAllRaw(requestParameters: TwitterClientControllerFindAllRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Array<object>>> {
        if (requestParameters.twitterName === null || requestParameters.twitterName === undefined) {
            throw new runtime.RequiredError('twitterName','Required parameter requestParameters.twitterName was null or undefined when calling twitterClientControllerFindAll.');
        }

        if (requestParameters.query === null || requestParameters.query === undefined) {
            throw new runtime.RequiredError('query','Required parameter requestParameters.query was null or undefined when calling twitterClientControllerFindAll.');
        }

        if (requestParameters.since === null || requestParameters.since === undefined) {
            throw new runtime.RequiredError('since','Required parameter requestParameters.since was null or undefined when calling twitterClientControllerFindAll.');
        }

        const queryParameters: any = {};

        if (requestParameters.twitterName !== undefined) {
            queryParameters['twitterName'] = requestParameters.twitterName;
        }

        if (requestParameters.query !== undefined) {
            queryParameters['query'] = requestParameters.query;
        }

        if (requestParameters.since !== undefined) {
            queryParameters['since'] = (requestParameters.since as any).toISOString();
        }

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/twitter-client`,
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse<any>(response);
    }

    /**
     */
    async twitterClientControllerFindAll(requestParameters: TwitterClientControllerFindAllRequest, initOverrides?: RequestInit): Promise<Array<object>> {
        const response = await this.twitterClientControllerFindAllRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
