/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import * as runtime from '../runtime';
import {
    CreateTriggerDto,
    CreateTriggerDtoFromJSON,
    CreateTriggerDtoToJSON,
    Trigger,
    TriggerFromJSON,
    TriggerToJSON,
    UpdateTriggerDto,
    UpdateTriggerDtoFromJSON,
    UpdateTriggerDtoToJSON,
} from '../models';

export interface TriggerControllerCreateRequest {
    botuuid: string;
    createTriggerDto: CreateTriggerDto;
}

export interface TriggerControllerGetOneRequest {
    botuuid: string;
    triggeruuid: string;
}

export interface TriggerControllerRemoveRequest {
    botuuid: string;
    triggeruuid: string;
}

export interface TriggerControllerUpdateRequest {
    botuuid: string;
    updateTriggerDto: UpdateTriggerDto;
}

/**
 * TriggersApi - interface
 * 
 * @export
 * @interface TriggersApiInterface
 */
export interface TriggersApiInterface {
    /**
     * 
     * @param {string} botuuid 
     * @param {CreateTriggerDto} createTriggerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TriggersApiInterface
     */
    triggerControllerCreateRaw(requestParameters: TriggerControllerCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>>;

    /**
     */
    triggerControllerCreate(requestParameters: TriggerControllerCreateRequest, initOverrides?: RequestInit): Promise<Trigger>;

    /**
     * 
     * @param {string} botuuid 
     * @param {string} triggeruuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TriggersApiInterface
     */
    triggerControllerGetOneRaw(requestParameters: TriggerControllerGetOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>>;

    /**
     */
    triggerControllerGetOne(requestParameters: TriggerControllerGetOneRequest, initOverrides?: RequestInit): Promise<Trigger>;

    /**
     * 
     * @param {string} botuuid 
     * @param {string} triggeruuid 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TriggersApiInterface
     */
    triggerControllerRemoveRaw(requestParameters: TriggerControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>>;

    /**
     */
    triggerControllerRemove(requestParameters: TriggerControllerRemoveRequest, initOverrides?: RequestInit): Promise<void>;

    /**
     * 
     * @param {string} botuuid 
     * @param {UpdateTriggerDto} updateTriggerDto 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TriggersApiInterface
     */
    triggerControllerUpdateRaw(requestParameters: TriggerControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>>;

    /**
     */
    triggerControllerUpdate(requestParameters: TriggerControllerUpdateRequest, initOverrides?: RequestInit): Promise<Trigger>;

}

/**
 * 
 */
export class TriggersApi extends runtime.BaseAPI implements TriggersApiInterface {

    /**
     */
    async triggerControllerCreateRaw(requestParameters: TriggerControllerCreateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>> {
        if (requestParameters.botuuid === null || requestParameters.botuuid === undefined) {
            throw new runtime.RequiredError('botuuid','Required parameter requestParameters.botuuid was null or undefined when calling triggerControllerCreate.');
        }

        if (requestParameters.createTriggerDto === null || requestParameters.createTriggerDto === undefined) {
            throw new runtime.RequiredError('createTriggerDto','Required parameter requestParameters.createTriggerDto was null or undefined when calling triggerControllerCreate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{botuuid}/trigger`.replace(`{${"botuuid"}}`, encodeURIComponent(String(requestParameters.botuuid))),
            method: 'POST',
            headers: headerParameters,
            query: queryParameters,
            body: CreateTriggerDtoToJSON(requestParameters.createTriggerDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerFromJSON(jsonValue));
    }

    /**
     */
    async triggerControllerCreate(requestParameters: TriggerControllerCreateRequest, initOverrides?: RequestInit): Promise<Trigger> {
        const response = await this.triggerControllerCreateRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async triggerControllerGetOneRaw(requestParameters: TriggerControllerGetOneRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>> {
        if (requestParameters.botuuid === null || requestParameters.botuuid === undefined) {
            throw new runtime.RequiredError('botuuid','Required parameter requestParameters.botuuid was null or undefined when calling triggerControllerGetOne.');
        }

        if (requestParameters.triggeruuid === null || requestParameters.triggeruuid === undefined) {
            throw new runtime.RequiredError('triggeruuid','Required parameter requestParameters.triggeruuid was null or undefined when calling triggerControllerGetOne.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{botuuid}/trigger/{triggeruuid}`.replace(`{${"botuuid"}}`, encodeURIComponent(String(requestParameters.botuuid))).replace(`{${"triggeruuid"}}`, encodeURIComponent(String(requestParameters.triggeruuid))),
            method: 'GET',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerFromJSON(jsonValue));
    }

    /**
     */
    async triggerControllerGetOne(requestParameters: TriggerControllerGetOneRequest, initOverrides?: RequestInit): Promise<Trigger> {
        const response = await this.triggerControllerGetOneRaw(requestParameters, initOverrides);
        return await response.value();
    }

    /**
     */
    async triggerControllerRemoveRaw(requestParameters: TriggerControllerRemoveRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<void>> {
        if (requestParameters.botuuid === null || requestParameters.botuuid === undefined) {
            throw new runtime.RequiredError('botuuid','Required parameter requestParameters.botuuid was null or undefined when calling triggerControllerRemove.');
        }

        if (requestParameters.triggeruuid === null || requestParameters.triggeruuid === undefined) {
            throw new runtime.RequiredError('triggeruuid','Required parameter requestParameters.triggeruuid was null or undefined when calling triggerControllerRemove.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{botuuid}/trigger/{triggeruuid}`.replace(`{${"botuuid"}}`, encodeURIComponent(String(requestParameters.botuuid))).replace(`{${"triggeruuid"}}`, encodeURIComponent(String(requestParameters.triggeruuid))),
            method: 'DELETE',
            headers: headerParameters,
            query: queryParameters,
        }, initOverrides);

        return new runtime.VoidApiResponse(response);
    }

    /**
     */
    async triggerControllerRemove(requestParameters: TriggerControllerRemoveRequest, initOverrides?: RequestInit): Promise<void> {
        await this.triggerControllerRemoveRaw(requestParameters, initOverrides);
    }

    /**
     */
    async triggerControllerUpdateRaw(requestParameters: TriggerControllerUpdateRequest, initOverrides?: RequestInit): Promise<runtime.ApiResponse<Trigger>> {
        if (requestParameters.botuuid === null || requestParameters.botuuid === undefined) {
            throw new runtime.RequiredError('botuuid','Required parameter requestParameters.botuuid was null or undefined when calling triggerControllerUpdate.');
        }

        if (requestParameters.updateTriggerDto === null || requestParameters.updateTriggerDto === undefined) {
            throw new runtime.RequiredError('updateTriggerDto','Required parameter requestParameters.updateTriggerDto was null or undefined when calling triggerControllerUpdate.');
        }

        const queryParameters: any = {};

        const headerParameters: runtime.HTTPHeaders = {};

        headerParameters['Content-Type'] = 'application/json';

        if (this.configuration && this.configuration.accessToken) {
            const token = this.configuration.accessToken;
            const tokenString = await token("bearer", []);

            if (tokenString) {
                headerParameters["Authorization"] = `Bearer ${tokenString}`;
            }
        }
        const response = await this.request({
            path: `/custom-bot/{botuuid}/trigger`.replace(`{${"botuuid"}}`, encodeURIComponent(String(requestParameters.botuuid))),
            method: 'PATCH',
            headers: headerParameters,
            query: queryParameters,
            body: UpdateTriggerDtoToJSON(requestParameters.updateTriggerDto),
        }, initOverrides);

        return new runtime.JSONApiResponse(response, (jsonValue) => TriggerFromJSON(jsonValue));
    }

    /**
     */
    async triggerControllerUpdate(requestParameters: TriggerControllerUpdateRequest, initOverrides?: RequestInit): Promise<Trigger> {
        const response = await this.triggerControllerUpdateRaw(requestParameters, initOverrides);
        return await response.value();
    }

}
