/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

/**
 * 
 * @export
 * @enum {string}
 */
export enum RunningStateEnum {
    STARTED = 'STARTED',
    STOPPED = 'STOPPED'
}

export function RunningStateEnumFromJSON(json: any): RunningStateEnum {
    return RunningStateEnumFromJSONTyped(json, false);
}

export function RunningStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): RunningStateEnum {
    return json as RunningStateEnum;
}

export function RunningStateEnumToJSON(value?: RunningStateEnum | null): any {
    return value as any;
}

