/* tslint:disable */
/* eslint-disable */
/**
 * Coin bot BE Api
 * Describes the backend api
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import {
    AllMetaTypes,
    AllMetaTypesFromJSON,
    AllMetaTypesFromJSONTyped,
    AllMetaTypesToJSON,
} from './';

/**
 * 
 * @export
 * @interface UpdateTriggerDto
 */
export interface UpdateTriggerDto {
    /**
     * 
     * @type {number}
     * @memberof UpdateTriggerDto
     */
    id: number;
    /**
     * 
     * @type {string}
     * @memberof UpdateTriggerDto
     */
    uuid: string;
    /**
     * 
     * @type {AllMetaTypes}
     * @memberof UpdateTriggerDto
     */
    allMeta: AllMetaTypes;
}

export function UpdateTriggerDtoFromJSON(json: any): UpdateTriggerDto {
    return UpdateTriggerDtoFromJSONTyped(json, false);
}

export function UpdateTriggerDtoFromJSONTyped(json: any, ignoreDiscriminator: boolean): UpdateTriggerDto {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'id': json['id'],
        'uuid': json['uuid'],
        'allMeta': AllMetaTypesFromJSON(json['allMeta']),
    };
}

export function UpdateTriggerDtoToJSON(value?: UpdateTriggerDto | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'id': value.id,
        'uuid': value.uuid,
        'allMeta': AllMetaTypesToJSON(value.allMeta),
    };
}

